# Generated by Django 4.1.7 on 2023-03-18 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripCategoria', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categoria de producto',
            },
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300, null=True)),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unidad', models.CharField(max_length=10)),
                ('existencia', models.IntegerField(null=True)),
                ('imgGrande', models.ImageField(null=True, upload_to='productos')),
                ('imgpeque', models.ImageField(null=True, upload_to='iconos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProductos.categoria')),
            ],
        ),
    ]
